### ISSUE TITLE
Disguise block texture oriented incorrectly.

### ISSUE THREAD

**Issue by brisingraerowing** [ZigTheHedge/slideemall#4] opened 2019-08-31 19:59 UTC
**Describe the bug**
I have sliders disguised as stone bricks, and the texture is oriented 90 degrees counterclockwise.

**To Reproduce**
Disguise a slider as stone bricks and look at the bottom side.

**Version information**
Forge version: 2838
Mod version: 1.0

**Crashlog (if any)**
N/A

**Any additional information**
![2019-08-31_15 55 18](https://user-images.githubusercontent.com/250409/64068589-3b683300-cc08-11e9-8afb-45c91db977b1.png)

**Comment by ZigTheHedge** [comment] 2019-09-02 05:40
Are you sure - that's the 1.0 version? Because I totally cannot reproduce it...
![2019-05-14_16 28 48](https://user-images.githubusercontent.com/2570571/64092409-5e582b80-cd5d-11e9-8a00-6f62d49f7e3b.png)

**Comment by ZigTheHedge** [comment] 2019-09-02 05:50
Fixed in 1.01

**Closed as completed by ZigTheHedge** 2019-09-02 05:50 UTC
Labels: bug

**Comment by brisingraerowing** [comment] 2019-09-02 13:37
Awesome!
